version: '2'
services:
  app:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    depends_on:
      - jenkis
  jenkins:
    image: jenkinsci/jenkins:2.2
    ports:
     - "8080:8080"
     - "50000:50000"
